@url = "http://localhost:3000"

//getting all
GET http://localhost:3000/allproducts HTTP/1.1

######
//creating new selle
POST http://localhost:3000/products  HTTP/1.1
Content-Type: application/json

{
     "id": "1110A",
    "gender": "male",
    "category": "necklace",
    "price": "234", 
    "name_of_product": "Necklace Holmes",
    "owner": "House Batibos",
    "main_color": "silver",
    "sec_color": "yellow",
    "currency": "cedis",
    "material": "steel",
    "dis_img": "prod-1.jpg"
    //"sec_imgs": [{}, {}, {}],

}



######
POST http://localhost:3000/upload HTTP/1.1
Content-Type:image/jpeg

{
    "dis_img":"C:\Users\HP\Pictures\Saved Pictures\avatar.png"
}