export class Product {
    constructor( id,gender,category,price,name,seller,seller_number,metals,metal_purity,product_weight,
    product_unit,
    metal_certification,
    main_color,
    sec_color,
    currency,
    createdAt,
    //updatedAt
   // dis_img,
   // sec_imgs
) {
      this.id = id // represents the id generated by the firestore
      this.gender = gender
      this.category = category
      this.price = price
      this.name = name
      this.seller = seller
      this.seller_number = seller_number
      this.metals = metals
      this.metal_purity = metal_purity
      this.product_weight = product_weight
      this.product_unit = product_unit
      this.metal_certification = metal_certification
      this.main_color = main_color
      this.sec_color = sec_color
      this.currency = currency
      this.createdAt = createdAt
      //this.updatedAt = updatedAt
     // this.dis_img = dis_img
     // this.sec_imgs = sec_imgs
  }
}